import { useEffect, useMemo, useRef, useState } from 'react';
import gsap from 'gsap';
import { Activity, Check, ChevronDown, Crosshair, Heart, LayoutGrid, Monitor, Moon, Search, Settings2, Star, Sun, Zap } from 'lucide-react';
import { bridge, type Snapshot, type Style } from '../bridge';

const demo:Snapshot={version:1,revision:0,theme:'dark',resolvedTheme:'dark',accent:'#67D4AE',overlay:true,activeId:'',selectedId:'',styles:[]};
function contrastText(hex:string){const value=hex.replace('#','');if(!/^[\da-f]{6}$/i.test(value))return '#10201a';const c=[0,2,4].map(i=>parseInt(value.slice(i,i+2),16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2]>.42?'#111615':'#fff'}
function Preview({item}:{item:Style}){const gap=Math.max(3,Math.min(18,item.gap*.65)),arm=Math.max(6,Math.min(24,item.armLength*.8)),w=Math.max(1,Math.min(5,item.thickness)),shape=item.shape;const lines=shape==='dot'||shape==='ring'?[]:[`M50 ${35-gap-arm}v${arm}`,...(item.tStyle?[]:[`M50 ${35+gap}v${arm}`]),`M${50-gap-arm} 35h${arm}`,`M${50+gap} 35h${arm}`];return <div className="preview" aria-hidden="true"><svg viewBox="0 0 100 70"><g transform="rotate(0 50 35)" stroke={item.color||'currentColor'} strokeOpacity={item.opacity/255} strokeWidth={w} strokeLinecap="square" fill="none">{shape==='circle_cross'&&<circle cx="50" cy="35" r={Math.max(6,Math.min(18,item.circleRadius*.9))}/>}{shape==='ring'&&<circle cx="50" cy="35" r={Math.max(8,Math.min(23,item.circleRadius))}/>}{shape==='square'&&<rect x="38" y="23" width="24" height="24"/>}{shape==='diamond'&&<path d="M50 20 65 35 50 50 35 35Z"/>}{shape==='bracket'&&<path d="M34 29v-6h8 M66 29v-6h-8 M34 41v6h8 M66 41v6h-8"/>}{lines.map((d,i)=><path key={i} d={d}/>)}{shape==='dot'&&<circle cx="50" cy="35" r={Math.max(2,w+1)} fill={item.color||'currentColor'}/>}{item.dot&&shape!=='dot'&&<circle cx="50" cy="35" r={Math.max(1.5,w+1)} fill={item.color||'currentColor'}/>}</g></svg></div>}
export function App(){const [state,setState]=useState<Snapshot>(bridge.snapshot??demo),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[page,setPage]=useState('Library'),[filter,setFilter]=useState('all'),[bridgeStatus,setBridgeStatus]=useState(bridge.status),[err,setErr]=useState('');const mainRef=useRef<HTMLElement>(null);useEffect(()=>bridge.subscribe(s=>{setState(s);setSelected(s.selectedId)}),[]);useEffect(()=>bridge.subscribeStatus(setBridgeStatus),[]);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const ctx=gsap.context(()=>{gsap.fromTo('.page-head',{y:4,opacity:.7},{y:0,opacity:1,duration:.16,ease:'power2.out'})},mainRef);return()=>ctx.revert()},[page]);
 const styles=useMemo(()=>state.styles.filter(s=>{const my=s.favorite||['custom','creator_grid','imported_pack','plugin_pack','legacy_pack'].includes(s.source);const category=filter==='all'||(filter==='my'&&my)||(filter==='favorites'&&s.favorite)||(filter==='creator'&&s.source==='creator_grid')||(filter==='imports'&&['imported_pack','plugin_pack','legacy_pack'].includes(s.source))||(filter==='custom'&&s.source==='custom');return (page!=='My Crosshairs'||my)&&category&&(s.name+' '+s.family+' '+s.source+' '+s.tags.join(' ')).toLowerCase().includes(query.toLowerCase())}),[state.styles,query,filter,page]);
 async function command(name:string,payload:Record<string,unknown>={}){try{const r=await bridge.send(name,payload);if(!r.ok)throw Error(r.error?.message??'Command failed');setErr('')}catch(e){setErr(String(e))}}
 const active=state.styles.find(s=>s.id===state.activeId); const picked=state.styles.find(s=>s.id===selected);
 return <div className="shell" data-theme={(state.resolvedTheme??state.theme)==='light'?'light':'dark'} style={{'--accent':state.accent, '--accent-ink':contrastText(state.accent)} as React.CSSProperties}>
  <aside className="rail"><div className="brand"><div className="brand-icon"><Crosshair size={20}/></div><div><b>Crosshair</b><small>OVERLAY CONTROL</small></div></div><div className="rail-label">WORKSPACE</div>{[['Home',Zap],['Library',LayoutGrid],['My Crosshairs',Star],['Creator',Crosshair],['Games',Monitor],['Settings',Settings2]].map(([name,Icon]:any)=><button key={name} className={'nav '+(page===name?'on':'')} onClick={()=>{if(name==='Creator'||name==='Games'||name==='Settings'||name==='Home'){void command('navigate',{page:name.toLowerCase()});return}setPage(name);setFilter('all');void command('navigate',{page:name==='My Crosshairs'?'my_crosshairs':'library'})}}><Icon size={17}/><span>{name}</span></button>)}<div className="rail-bottom"><div className={'runtime '+(state.overlay?'running':'')}><i/><div><b>{state.overlay?'Overlay running':'Overlay paused'}</b><small>{active?.name??'No active style'}</small></div><button aria-label="Toggle overlay" onClick={()=>void command('setOverlay',{enabled:!state.overlay})}><Activity size={16}/></button></div><button className="native" onClick={()=>void command('toggleNative',{})}>Switch to classic controls</button><small className="shortcut-hint">Switch back with Ctrl + Shift + N</small></div></aside>
  <main className="main" ref={mainRef}><header><div className="crumb">Workspace <span>/</span> {page}</div><div className="head-actions"><span className="status"><i className={bridgeStatus==='connected'?'':'offline'}/> {bridgeStatus==='connected'?'Native runtime connected':bridgeStatus==='failed'?'Native bridge unavailable':'Connecting to runtime…'}</span><button className="icon-button" aria-label="Toggle theme" disabled={bridgeStatus!=='connected'} onClick={()=>void command('setTheme',{theme:state.theme==='dark'?'light':'dark'})}>{state.theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button></div></header>
  <section className="page-head"><div><div className="eyebrow">PRECISION TOOLKIT</div><h1>{page}</h1><p>Choose a crosshair, preview it, then apply it to your overlay.</p></div>{page==='Library'&&<button className="primary" onClick={()=>void command('setOverlay',{enabled:!state.overlay})}><Activity size={16}/>{state.overlay?'Pause overlay':'Start overlay'}</button>}</section>
  {(err||bridgeStatus==='failed')&&<div className="error" role="alert">{err||'The native control bridge did not start. Switch to classic controls with Ctrl + Shift + N.'}</div>}
  <section className="library-layout"><div className="catalog"><div className="toolbar"><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search crosshairs" aria-label="Search crosshairs"/><kbd>Ctrl K</kbd></label><select className="filter" aria-label="Filter crosshairs" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{page==='My Crosshairs'?'My styles':'All styles'}</option><option value="favorites">Favorites</option><option value="creator">Creator</option><option value="imports">Imports</option><option value="custom">Custom</option></select><button className="icon-button" aria-label="Show favorites" onClick={()=>{setPage('My Crosshairs');setFilter('favorites');void command('navigate',{page:'my_crosshairs'})}}><Heart size={16}/></button></div><div className="result-line"><span>{styles.length} crosshairs</span><span>{page==='My Crosshairs'?'Your collection':'Library'}</span></div><div className="grid">{styles.map(s=><button key={s.id} className={'card '+(selected===s.id?'selected':'')} onClick={()=>{setSelected(s.id);void command('selectStyle',{styleId:s.id})}} onDoubleClick={()=>void command('activateStyle',{styleId:s.id})} aria-pressed={selected===s.id} aria-label={`${s.name}, ${s.family}${s.active?', active':''}`} title={s.name}><div className="card-top"><span className="tag">{s.source}</span><span className={'favorite '+(s.favorite?'saved':'')} role="button" tabIndex={0} aria-label={s.favorite?'Remove favorite':'Add favorite'} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();void command('toggleFavorite',{styleId:s.id})}}} onClick={e=>{e.stopPropagation();void command('toggleFavorite',{styleId:s.id})}}><Heart size={15} fill={s.favorite?'currentColor':'none'}/></span></div><Preview item={s}/><div className="card-meta"><div><b>{s.name}</b><small>{s.family}</small></div>{s.active&&<span className="live">ACTIVE</span>}</div></button>)}</div>{!styles.length&&<div className="empty"><Crosshair size={24}/><b>No matching crosshairs</b><span>Try another name or tag.</span></div>}</div>
  <aside className="inspector"><div className="inspect-title"><div><span className="eyebrow">PREVIEW</span><h2>{picked?.name??'Select a crosshair'}</h2></div><button className="icon-button" aria-label="Favorite" onClick={()=>picked&&void command('toggleFavorite',{styleId:picked.id})}><Heart size={16}/></button></div><div className="large-preview">{picked?<Preview item={picked}/>:<Crosshair size={36} strokeWidth={1.2}/>}<span>Preview only</span></div><div className="inspect-details"><div><small>FAMILY</small><b>{picked?.family??'—'}</b></div><div><small>SOURCE</small><b>{picked?.source??'—'}</b></div></div><div className="inspect-actions"><button className="primary wide" disabled={!picked} onClick={()=>picked&&void command('activateStyle',{styleId:picked.id})}><Check size={16}/> Use this crosshair</button><button className="secondary wide" disabled={!picked} onClick={()=>picked&&void command('openDetail',{styleId:picked.id})}>Edit details</button></div><div className="active-note"><span className="pulse"/><div><b>Active in overlay</b><small>{active?.name??'None selected'}</small></div></div></aside></section>
  <footer><span>Crosshair Overlay <b>•</b> v1.0</span><span><span className="connected"/> Connected to Windows runtime</span></footer>
 </main></div>}
